#!/usr/bin/env python3
"""
Convert GEMM shapes (from extract_shapes.py) into a TensileLite benchmark YAML.

TensileLite benchmarks a set of GEMM problems and produces library logic (YAML)
mapping each problem size to the optimal kernel config for the target GPU.
This script generates the input problem spec for that process.
"""

import argparse
import json
import sys
from pathlib import Path


# Map GGML dtype names to Tensile DataType codes
# Tensile operates on compute types, not storage types.
# Quantized types (Q4_0 etc.) dequantize to fp16/bf16 before GEMM.
DTYPE_TO_TENSILE = {
    "F32":   {"DataType": "s",  "ComputeDataType": "s"},
    "F16":   {"DataType": "h",  "ComputeDataType": "s"},
    "BF16":  {"DataType": "b",  "ComputeDataType": "s"},
    # Quantized types: actual GEMM runs in fp16 after dequant
    "Q4_0":  {"DataType": "h",  "ComputeDataType": "s"},
    "Q4_1":  {"DataType": "h",  "ComputeDataType": "s"},
    "Q4_K":  {"DataType": "h",  "ComputeDataType": "s"},
    "Q5_K":  {"DataType": "h",  "ComputeDataType": "s"},
    "Q6_K":  {"DataType": "h",  "ComputeDataType": "s"},
    "Q8_0":  {"DataType": "h",  "ComputeDataType": "s"},
    "Q2_K":  {"DataType": "h",  "ComputeDataType": "s"},
    "Q3_K":  {"DataType": "h",  "ComputeDataType": "s"},
}
DEFAULT_DTYPE = {"DataType": "h", "ComputeDataType": "s"}


# WMMA MatrixInstruction parameters for RDNA2 (gfx103x).
# Format: [MIA, NIB, K, B, NumThreads, MIBlockM, MIBlockN, MIToMFMA_M, MIToMFMA_N]
# RDNA2 has WMMA 16x16x16 but no MFMA. We enumerate tile size combinations.
_WMMA_RDNA2_INSTRUCTIONS = [
    # [16,16,16,1,1, MIBlockM, MIWavefrontM, MIWavefrontN, 1]
    *[[16, 16, 16, 1, 1, mb, wm, wn, 1]
      for mb in [1]
      for wm in [1, 2, 4, 8]
      for wn in [1, 2, 4]],
]

# Tile parameters to sweep — wave32 (gfx1032 default)
_RDNA2_FORK_PARAMS = [
    ("MatrixInstruction", _WMMA_RDNA2_INSTRUCTIONS),
    ("DepthU",            [16, 32, 64, 128]),
    ("GlobalSplitU",      [1, 2, 4, 8]),
    ("GlobalSplitUAlgorithm", ["MultipleBuffer"]),
    ("PrefetchGlobalRead", [1, 2]),
    ("PrefetchLocalRead",  [1]),
    ("WorkGroupMapping",   [1, 4]),
    ("StaggerU",          [0, 4]),
    ("StaggerUStride",    [256]),
    ("VectorWidthA",      [-1]),
    ("VectorWidthB",      [-1]),
    ("GlobalReadVectorWidthA", [-1]),
    ("GlobalReadVectorWidthB", [-1]),
    ("StoreVectorWidth",  [-1]),
]


def group_shapes_by_dtype(shapes: list) -> dict:
    """Group shapes by their Tensile data type config."""
    groups = {}
    for shape in shapes:
        tensile_dtype = DTYPE_TO_TENSILE.get(shape["dtype"], DEFAULT_DTYPE)
        key = (tensile_dtype["DataType"], tensile_dtype["ComputeDataType"])
        if key not in groups:
            groups[key] = {"tensile": tensile_dtype, "shapes": []}
        groups[key]["shapes"].append(shape)
    return groups


def _is_rdna2(gfx_target: str) -> bool:
    return gfx_target.startswith("gfx103")


def generate_yaml(result: dict, gfx_target: str, output_path: Path) -> None:
    model_name = result["model"]
    groups = group_shapes_by_dtype(result["shapes"])

    lines = []
    lines.append(f"# TensileLite benchmark config for {model_name} on {gfx_target}")
    lines.append(f"# Generated by gguf-tune/generate_tensile_config.py")
    lines.append(f"# Architecture: {result['architecture']}")
    lines.append(f"# Unique shapes: {result['unique_shapes']}")
    lines.append("")
    lines.append("GlobalParameters:")
    lines.append("  PrintLevel: 1")
    lines.append("  ForceRedoBenchmarkProblems: True")
    lines.append("  PrintSolutionRejectionReason: False")
    lines.append("  NewClient: 2")
    lines.append("  KernelTime: True")
    lines.append("  NumWarmups: 10")
    lines.append("  EnqueuesPerSync: 10")
    lines.append("  NumElementsToValidate: 0")
    lines.append("  SkipSlowSolutionRatio: 0.5")
    lines.append(f"  Platform: 0")
    lines.append(f"  Device: 0")
    lines.append(f"  LibraryFormat: yaml")
    lines.append("")
    lines.append("BenchmarkProblems:")

    for (dt, cdt), group in groups.items():
        tensile = group["tensile"]
        shapes = group["shapes"]

        lines.append(f"  - # DataType={dt} ComputeDataType={cdt}")
        lines.append(f"    - OperationType: GEMM")
        lines.append(f"      DataType: {tensile['DataType']}")
        lines.append(f"      ComputeDataType: {tensile['ComputeDataType']}")
        lines.append(f"      TransposeA: N")
        lines.append(f"      TransposeB: T")
        lines.append(f"      UseBeta: True")
        lines.append(f"      HighPrecisionAccumulate: True")
        lines.append(f"      Batched: True")
        lines.append(f"    - BenchmarkForks: 0")
        lines.append(f"      InitialSolutionParameters:")
        lines.append(f"      BenchmarkCommonParameters:")
        lines.append(f"        - KernelLanguage: [Assembly]")

        fork_params = _RDNA2_FORK_PARAMS if _is_rdna2(gfx_target) else []
        if fork_params:
            lines.append(f"      ForkParameters:")
            for param_name, values in fork_params:
                if isinstance(values[0], list):
                    lines.append(f"        - {param_name}:")
                    for v in values:
                        lines.append(f"          - {v}")
                else:
                    vals_str = ", ".join(str(v) for v in values)
                    lines.append(f"        - {param_name}: [{vals_str}]")
        else:
            lines.append(f"      ForkParameters:")
        lines.append(f"      BenchmarkForkParameters:")
        lines.append(f"      JoinParameters:")
        lines.append(f"      BenchmarkJoinParameters:")
        lines.append(f"      BenchmarkFinalParameters:")
        lines.append(f"        - ProblemSizes:")

        seen = set()
        for shape in shapes:
            key = (shape["M"], shape["N"], shape["K"])
            if key in seen:
                continue
            seen.add(key)
            # Tensile ProblemSizes format: [M, N, batch, K]
            lines.append(f"          - Exact: [{shape['M']}, {shape['N']}, 1, {shape['K']}]")
        lines.append("")

    output_path.write_text("\n".join(lines))
    print(f"Written: {output_path}", file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(
        description="Generate TensileLite benchmark YAML from GGUF shape data"
    )
    parser.add_argument(
        "shapes_json", type=Path,
        help="JSON file from extract_shapes.py (or - for stdin)"
    )
    parser.add_argument(
        "--gfx", default="gfx1032",
        help="Target GPU architecture (default: gfx1032)"
    )
    parser.add_argument(
        "--output", type=Path, default=None,
        help="Output YAML path (default: <model>_<gfx>.yaml)"
    )
    args = parser.parse_args()

    if str(args.shapes_json) == "-":
        result = json.load(sys.stdin)
    else:
        result = json.loads(args.shapes_json.read_text())

    out = args.output or Path(f"{result['architecture']}_{args.gfx}_benchmark.yaml")
    generate_yaml(result, args.gfx, out)


if __name__ == "__main__":
    main()
